### ISSUE TITLE
Appcache & url parameters aren't compatible

### ISSUE THREAD

**Issue by PriceChild** [PriceChild/cofg#2]
This makes the idea of storing bookmarks with the query parameters less useful.

Need to consider what we can do with localstorage.

**Comment by JoePricey** [comment]
fragments used instead: https://github.com/PriceChild/cofg/commit/4ba1df6ec5339a398625d797be9e57bfc9f697f5

Rudimentary save/load support: https://github.com/PriceChild/cofg/commit/47077b1b42f62fe6f936f78de203a047744d281c
